// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnU8YhzyILCGgIo6j1mKWT50-i2cqYFFc',
    appId: '1:432325702637:web:0a8c888f07f0db366bede4',
    messagingSenderId: '432325702637',
    projectId: 'catfe-app',
    authDomain: 'catfe-app.firebaseapp.com',
    storageBucket: 'catfe-app.firebasestorage.app',
    measurementId: 'G-7MYDCHT6NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvaNYvaLS_vAuB7FGScL8WMuO_epq9wQY',
    appId: '1:432325702637:android:d06f05d4925aae9f6bede4',
    messagingSenderId: '432325702637',
    projectId: 'catfe-app',
    storageBucket: 'catfe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuwfy6385B9KmeURKFfxV0kwSnO5DiF_s',
    appId: '1:432325702637:ios:746de6d493744b346bede4',
    messagingSenderId: '432325702637',
    projectId: 'catfe-app',
    storageBucket: 'catfe-app.firebasestorage.app',
    iosBundleId: 'com.example.catfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuwfy6385B9KmeURKFfxV0kwSnO5DiF_s',
    appId: '1:432325702637:ios:746de6d493744b346bede4',
    messagingSenderId: '432325702637',
    projectId: 'catfe-app',
    storageBucket: 'catfe-app.firebasestorage.app',
    iosBundleId: 'com.example.catfe',
  );
}
